### ISSUE TITLE
性能问题咨询

### ISSUE THREAD

**Issue by WhZzi** [ydf0509/nb_http_client#5]
目前的对象属性在初始化时就需要固定host。
但是个别项目中对于请求的host可能会一直需要切换,一直去重复初始化新的host，新的对象池HttpOperator，去请求不同的url对性能会有影响吗？ (需要请求的host无法预知，只能遇到再去初始化)

**Comment by ydf0509** [comment]
为什么host有很多呢，你爬虫也是爬某个网站吧。

**Comment by ydf0509** [comment]
现在的api的确是这样，不适合请求很多不同的host，需要仔细研究。如果你有10个网站要爬，可以实例化10个吧应该。

**Comment by WhZzi** [comment]
> 现在的api的确是这样，不适合请求很多不同的host，需要仔细研究。如果你有10个网站要爬，可以实例化10个吧应该。

我原本也是这样想的，每个host适配一个，但是个别有项目需要大量并发采集直播流,m3u8里的切片每个host都有在变,看来我的需求比较病态,可能不方便适配大佬的库。

**Comment by ydf0509** [comment]
httpclient可能更合适公司内部的rpc或者内部服务之间的调用，爬虫的话，cpu效率并不是最重要的，那就用requets。

**Comment by WhZzi** [comment]
> 

好嘞，感谢大佬的耐心回复。
